// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwRjcydSGH8YNzTU-KLNjoDqZkux4Z2Ak',
    appId: '1:618096157533:web:626fa99eb56909f63afeb4',
    messagingSenderId: '618096157533',
    projectId: 'visicheck-12e19',
    authDomain: 'visicheck-12e19.firebaseapp.com',
    storageBucket: 'visicheck-12e19.appspot.com',
    measurementId: 'G-7Y2WTDVYXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD56lGOZpB786q_UFwArVQ7lOHnaBwW6d8',
    appId: '1:618096157533:android:f136bf4422c226d63afeb4',
    messagingSenderId: '618096157533',
    projectId: 'visicheck-12e19',
    storageBucket: 'visicheck-12e19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZyZXSwhDSug5vaaqAkiyhGdVBEMFtUK4',
    appId: '1:618096157533:ios:0602eaa8dfc0afd83afeb4',
    messagingSenderId: '618096157533',
    projectId: 'visicheck-12e19',
    storageBucket: 'visicheck-12e19.appspot.com',
    iosBundleId: 'com.example.visicheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZyZXSwhDSug5vaaqAkiyhGdVBEMFtUK4',
    appId: '1:618096157533:ios:0602eaa8dfc0afd83afeb4',
    messagingSenderId: '618096157533',
    projectId: 'visicheck-12e19',
    storageBucket: 'visicheck-12e19.appspot.com',
    iosBundleId: 'com.example.visicheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwRjcydSGH8YNzTU-KLNjoDqZkux4Z2Ak',
    appId: '1:618096157533:web:98448819102780a53afeb4',
    messagingSenderId: '618096157533',
    projectId: 'visicheck-12e19',
    authDomain: 'visicheck-12e19.firebaseapp.com',
    storageBucket: 'visicheck-12e19.appspot.com',
    measurementId: 'G-KP4FQ9LCWD',
  );
}
