import 'package:flutter/material.dart';

class ViewAttendanceTable extends StatefulWidget {
  ViewAttendanceTable({super.key});

  final List<int> rollno = [
    101,
    102,
    103,
    104,
    105,
    106,
    107,
    108,
    109,
    110,
    111,
    112,
    113,
    114,
    115,
    116,
    117,
    118,
    119,
    120,
    121,
    122,
    123,
    124,
    125,
    126,
    127,
    128,
    129,
    130,
    131,
    132,
    133,
    134,
    135,
    136,
    137,
    138,
    139,
    140,
    141,
    142,
    143,
    144,
    145,
    146,
    147,
    148,
    149,
    150,
    151,
    152,
    153,
    154,
    155,
    156,
    157,
    158,
    159,
    160
  ];

  final List<String> name = [
    "Alice",
    "Bob",
    "Charlie",
    "David",
    "Eva",
    "Frank",
    "Grace",
    "Hannah",
    "Ian",
    "Jack",
    "Karen",
    "Liam",
    "Mia",
    "Nina",
    "Oscar",
    "Paul",
    "Quinn",
    "Rose",
    "Sam",
    "Tina",
    "Uma",
    "Vince",
    "Wendy",
    "Xander",
    "Yara",
    "Zane",
    "Amber",
    "Brian",
    "Chloe",
    "Derek",
    "Ellie",
    "Finn",
    "Georgia",
    "Harry",
    "Isla",
    "Jake",
    "Kara",
    "Leo",
    "Megan",
    "Noah",
    "Olivia",
    "Pete",
    "Quincy",
    "Rachel",
    "Sophie",
    "Tom",
    "Ursula",
    "Victor",
    "Will",
    "Xena",
    "Yasmine",
    "Zack",
    "Ava",
    "Ben",
    "Clara",
    "Daniel",
    "Ella",
    "Fred",
    "Gina",
    "Henry"
  ];

  final List<int> age = [
    25,
    30,
    35,
    28,
    22,
    40,
    26,
    29,
    32,
    27,
    34,
    23,
    31,
    24,
    38,
    33,
    36,
    21,
    39,
    37,
    20,
    45,
    41,
    42,
    43,
    44,
    48,
    46,
    49,
    47,
    50,
    53,
    51,
    54,
    52,
    55,
    57,
    56,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79
  ];
  @override
  State<ViewAttendanceTable> createState() => _ViewAttendanceTableState();
}

class _ViewAttendanceTableState extends State<ViewAttendanceTable> {
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: DataTable(
        border: TableBorder.all(
          color: Colors.white70,
          width: 1.5,
          borderRadius: const BorderRadius.all(Radius.circular(3)),
        ),
        columns: <DataColumn>[
          DataColumn(
            label: Expanded(
              child: Text(
                'Roll No',
                style:
                    TextStyle(fontStyle: FontStyle.italic, color: Theme.of(context).colorScheme.onBackground),
              ),
            ),
          ),
          DataColumn(
            label: Expanded(
              child: Text(
                'Name',
                style:
                    TextStyle(fontStyle: FontStyle.italic, color: Theme.of(context).colorScheme.onBackground),
              ),
            ),
          ),
          DataColumn(
            label: Expanded(
              child: Text(
                'Age',
                style:
                    TextStyle(fontStyle: FontStyle.italic, color: Theme.of(context).colorScheme.onBackground),
              ),
            ),
          ),
        ],
        rows: <DataRow>[
          for (int i = 0; i < 60; i++)
            DataRow(
              cells: <DataCell>[
                DataCell(Text(widget.rollno[i].toString(),
                    style: const TextStyle(
                        color: Color.fromARGB(223, 255, 255, 255)))),
                DataCell(Text(widget.name[i],
                    style: const TextStyle(
                        color: Color.fromARGB(223, 255, 255, 255)))),
                DataCell(Text(widget.age[i].toString(),
                    style: const TextStyle(
                        color: Color.fromARGB(223, 255, 255, 255)))),
              ],
            ),
        ],
      ),
    );
  }
}
